language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build

services:
  - mysql

before_script:
  - wget https://repo.mysql.com//mysql-apt-config_0.8.10-1_all.deb
  - sudo dpkg -i mysql-apt-config_0.8.10-1_all.deb
  - sudo apt-get update -q
  - sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server
  - sudo systemctl restart mysql
  - sudo mysql_upgrade
  - mysql -u root < bookstore.sql
  - sudo service mysql restart

# Install the codecov pip dependency
install:
  - pip install -r requirements.txt

# Run the unit test
script:
  - export PATHONPATH=`pwd`
  - coverage run --timid --branch --source fe,be --concurrency=thread -m pytest -v --ignore=fe/data

# Push the results back to codecov
after_success:
  - coverage combine
  - coverage report
  - codecov
